#!/bin/bash -xe
DATESTAMP=`date --iso`
VERSION=v1.1
ARCHIVE=~/tool/DAP-FTSCollector/archives/archive.sql

cd http
rm -f archive.sql csv.zip dataset.csv indicator.csv value.csv sql.zip all.zip
cat $ARCHIVE | sqlite3 ../ocha.db
zip csv.zip dataset.csv indicator.csv value.csv
zip sql.zip ../ocha.db
mkdir -p $VERSION
echo $DATESTAMP > $VERSION/DATESTAMP
mv *.csv $VERSION
mv *.zip $VERSION
echo "all ok"
